Sprint 15
mp3moto/Tracker pull request #2
Opened 2023-03-17 21:39 UTC by mp3moto

2023-03-19 09:56 UTC, IBDesignable requested changes
Сейчас выглядит не доделанным счетчик вопросов, он должен был работать еще в предыдущем модуле, но если не успел - то надо доделать сейчас. Также не очень понятно как работает и работает ли трекер привычек: при добавлении в пустое приложение привычки я не вижу обновления экрана ни на одном дне недели в прошлом/будущем.

2023-03-19 09:56 UTC, IBDesignable commented on Tracker/DataStore/CategoryStore.swift
> +    var dataStore: DataStore
Зачем доступ из вне? Давай инкапсулируем, и все обращение к dataStore только через функции.

Поправить нужно здесь и в остальных местах проекта, если повторяется

2023-03-19 09:56 UTC, IBDesignable commented on Tracker/DataStore/CategoryStore.swift
> +        }
Здесь можно пользоваться опциональным try: 
```suggestion
        return try? dataStore.getCategory(id)
```

Так как тебе не нужно обрабатывать ошибку, в случае таковой просто вернется nil. Можно поправить здесь и далее по проекту

2023-03-19 09:56 UTC, IBDesignable commented on Tracker/DataStore/DataStore.swift
> +        }
Можешь объяснить что этот код делает?

Зачем выставлять searchQuery в пустую строку, и в каком случае будет работать  `searchQuery.count > 0`?

2023-03-19 09:56 UTC, IBDesignable commented on Tracker/DataStore/DataStore.swift
> +    func unpackShedule(_ packed: Int32) -> Schedule {
Schedule – попробуй настроить проверку правописания 

https://sarunw.com/posts/spell-checking-in-xcode/

2023-03-19 09:56 UTC, IBDesignable commented on Tracker/DataStore/DataStore.swift
> +        )
Кажется эта функция не часть ответственность этого класса. Давай унесем в экстеншен к структуре, и как минимум упростим: `packed & 64 == 64 ? true : false` -> `packed & 64 == 64`.

Кстати интересное решение 👍🏻 Я бы собрала из более читаемого и понятного варианта с Codable от Set<DayOfWeek>  – CoreData умеет хранить объекты типа Data, а работать с енамами приятнее. 

Расскажешь что навело тебя на подобное решение?

2023-03-19 09:56 UTC, IBDesignable commented on Tracker/DataStore/DataStore.swift
> +    }
этот код тоже следует вынести из этого класса, можно тоже в экстеншен к типу дейтпикера (dateFromDatePicker)

2023-03-19 09:56 UTC, IBDesignable commented on Tracker/DataStore/DataStore.swift
> +                        )
в целом это тоже могло быть конвертором из TrackerDataObject -> Tracker

2023-03-19 09:56 UTC, IBDesignable commented on Tracker/DataStore/DataStore.swift
> +    var searchQuery: String = ""
Я думаю, что тебе стоило реализовать общие методы в DataStore, которые могли вернуть тебе некоторый объект, а в CategoryStore/TackerRecordStore/TrackerStore – готовить запросы и делать всю работу по конвертации данных во вьюмодели приложения. 

Сейчас этот класс похож на большую лапшу, его сложно читать и отслеживать ответсвтенности: уже еле укладывается в 400 строк. Это никуда не годится: представь, что ты в приложение добавляешь трекер шагов. Тебе понадобятся новые модели, чтобы описывать новые записи. И что тогда? снова гетеры-сеттеры здесь описывать? Это не рационально. 

Вот небольшой пример, что имею ввиду:
https://gist.github.com/ezequieloliveiralima/c970636cc643469352c46e908eb23271

Этот комментарий опционален, но достаточно критичный чтобы не отправлять его в долгий ящик

2023-03-19 09:56 UTC, IBDesignable commented on Tracker/DataStore/TrackerStore.swift
> +
Здесь и далее в других примерах, нужно соблюдать порядок: 

- свойства 
- вычисляемые свойства
- иниты, оверрайды
- публичные
- приватные методы

2023-03-19 09:56 UTC, IBDesignable commented on Tracker/Helpers/Constants.swift
> +struct const {
Все типы в CamelCase

2023-03-19 09:56 UTC, IBDesignable commented on Tracker/Screens/Category/CategoriesViewController.swift
> +        if let _ = data?.getCategories().count {
а что здесь хотелось проверить? может быть достаточно data?.getCategories() != nil ?

2023-03-19 13:39 UTC, mp3moto commented on Tracker/DataStore/DataStore.swift
> +        }
searchQuery.count срабатывает, когда мы выполняем поиск. Мне приходится принудительно обнулять эту переменную, потому что в если мы нажимаем cancel в строке поиска, то значение в поисковой строке так и остается последним

2023-03-19 13:42 UTC, mp3moto commented on Tracker/DataStore/DataStore.swift
> +        )
Мне по работе в сфере автоматизации производственных процессов часто приходится работать с упакованными в Int16 данными. Поэтому этот вариант - первое, что пришло мне в голову )

2023-03-19 13:48 UTC, mp3moto commented on Tracker/Screens/Category/CategoriesViewController.swift
> +        if let _ = data?.getCategories().count {
скажите, выражение != nil не считается плохим тоном? Нас, вроде бы, учили это проверять через if let, а != nil только если if let  в конкретном случае неудобен

2023-03-19 13:53 UTC, mp3moto commented on Tracker/DataStore/CategoryStore.swift
> +    var dataStore: DataStore
@IBDesignable не совсем понял про доступ извне. Если речь идет о var dataStore, то могу сказать, что из-за требования Import CoreData только в одном файле мне пришлось его единственный экземпляр через зависимости распространить везде, где нужна работа с ним. Или другое имелось в виду?

2023-03-19 20:15 UTC, mp3moto commented on Tracker/DataStore/DataStore.swift
> +    var searchQuery: String = ""
@IBDesignable обещаю не откладывать в долгий ящик и полностью осознаю, что это худший файл во всем проекте. Сейчас хотелось бы догнать по теории, а к следующему спринту уже навести порядок в этом месте

2023-03-19 20:55 UTC, mp3moto commented on Tracker/DataStore/DataStore.swift
> -        case "tracker": maxId = trackers.max(by: { a, b in a.id < b.id })?.id
Изменил реализацию на "не очень красивую", но более надежную. Эта давала не всегда правильный результат

2023-03-20 12:41 UTC, IBDesignable commented on Tracker/DataStore/CategoryStore.swift
> +    var dataStore: DataStore
это верно сделано. Извини, здесь я имею ввиду, что у тебя зависимость торчит наружу -- ее нужно прикрыть private

2023-03-20 12:45 UTC, IBDesignable commented on Tracker/Screens/Category/CategoriesViewController.swift
> +        if let _ = data?.getCategories().count {
Все просто:
1) Тебе нужно работать с опциональной переменной? Если да используй `if let a = a`, а потом делай на новой копии все что тебе нужно. У тебя не должно быть такого кода `a != nil ? a! : b`
2) дальше не требуется работать со значением, а нужно только проверить опциональность? используй сравнение с nil == или != (или иногда удобно в свитче `case .none = a`).

2023-03-20 13:02 UTC, IBDesignable commented on Tracker/DataStore/DataStore.swift
> -        case "tracker": maxId = trackers.max(by: { a, b in a.id < b.id })?.id
оп-паа)

как же я так пропустила этот код. Вообще в Swift не принято работать со строками и как только у тебя появляется нечто подобное, стоит вводить новый тип enum EntityType { case category, tracker }  так и со строками не придется рабоать и дефолт уйдет избыточный

2023-03-20 13:18 UTC, IBDesignable commented
Фетч запрос имеет странную сортировку, когда нажимаешь выполненно-невыполненно очень дерганно и неожиданно обновляется коллекция. Для пользователя это может быть больно. Предлагаю поисследовать и сделать так, чтобы список был отсортирован по какому-то более стабильному признаку. 
![RocketSim_Recording_iPhone_14_Pro_2023-03-20_15 08 50](https://user-images.githubusercontent.com/20269264/226348324-65123014-f880-4d3b-a701-408ed6e0452d.gif)

Обрати внимание, что ты также позволяешь вносить пометки в будущем – обычно этот стейт делают невозможным, например нельзя перейти на следующий день, или нельзя отчекбоксить карточку. (второй здесь уместнее, потому что я хочу смотреть запланированные дела)

И второй момент, я могу захотеть сделать отметки в прошлом, но к текущему дню статистика "сколько дней/раз"  я это делала ведется как будто только в рамках одного дня, а должна была суммироваться.
![RocketSim_Recording_iPhone_14_Pro_2023-03-20_15 11 52](https://user-images.githubusercontent.com/121577115/226349827-ec9453ec-f01c-47f4-829e-3d282b823e17.gif)

2023-03-20 13:22 UTC, IBDesignable commented on Tracker/DataStore/DataStore.swift
> -        case "tracker": maxId = trackers.max(by: { a, b in a.id < b.id })?.id
> Изменил реализацию на "не очень красивую", но более надежную. Эта давала не всегда правильный результат

новая версия более читаемая. тут не поспоришь.

2023-03-20 17:05 UTC, mp3moto commented
@IBDesignable Благодарю Вас за самый строгий и полезный для меня ревью! Это невозможно оценить - это бесценно!

2023-04-13 08:42 UTC, closed without merging